# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Pre-requisites
      - run: python3 -m pip install sphinx furo
      
      - name: Populate Docs
      - run: sphinx-apidoc --force -o docs/source/ discord-linker-pythonAPI/
      
      - name: Build
      - run: cd docs; make html; cd ..
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Move HTML
      - run: mv docs/build/html ./
      
      - name: Delete build directory
      - run: rm -rf docs/build
      
      - name: Move HTML
      - run: mv html/* docs/*
      
      - name: Delete empty HTML directory
      - run: rm -rf html
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
